---
title: "Материалы"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
---
# Регрессионный анализ: панельные данные и каузальность

<a href="https://disk.yandex.ru/d/4DB4BVGGpk-nhA" title=>Ссылка на общую папку с литературой</a>  
Папка будет пополняться в процессе изучения материала. 

### Обозначения

`r  shiny::icon("scroll")` -- презентация / конспект занятия / семинарский листочек

`r  shiny::icon("readme")` -- Reading

`r  shiny::icon("desktop")` -- материалы для практикума (данные, код)

`r  shiny::icon("pencil")` -- задание 
 
## Занятие 1
 
Тема: О чем курс и каковы правила игры? 
  
`r  shiny::icon("scroll")` <a href="RAPDC_intro_2022.pdf" title=>Introduction</a> 
 
Домашнее задание: 

`r  shiny::icon("readme")`  <a href="https://disk.yandex.ru/i/1xED4VRC2pIEyw" title=>Lundberg et al., 2021</a>  

## Занятие 2
 
Тема: Эндогенность и ее источники: повторение. 
Введение в анализ панельных данных: модели с фиксированными эффектами   
  
`r  shiny::icon("scroll")` <a href="RAPDC_lecture1_endo_2022.pdf" title=>Эндогенность: повторение</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_seminar1_2022.pdf" title=>Семинарский листочек 1</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_class2_12.09.html" title=>Конспект от 12.09</a> 

`r  shiny::icon("desktop")` <a href="RAPDC_lecture1_example1.rds" title=>RAPDC_lecture1_example1.rds</a> 
 
Домашнее задание: 

`r  shiny::icon("readme")`  <a href="https://disk.yandex.ru/i/G9DO5ZMwYmP2Mw" title=>Stock, Watson, Chapter 10 (10.1 - 10.3)</a>  

Дополнительно: `r  shiny::icon("readme")`  <a href="https://disk.yandex.ru/i/jckSVZKWPqWCMg" title=>Магнус, Катышев, Пересецкий, разделы 13.1 - 13.3</a>  

## Занятие 3
 
Тема: FE-модели: получение оценки коэффициента при предикторе. Альтернатива: RE-модель  

`r  shiny::icon("scroll")` <a href="RAPDC_lecture2.html" title=>Конспект от 19.09</a> 

## Занятие 4
 
Тема: RE-модель: спецификация, (F)GLS, сравнение с FE-моделью

`r  shiny::icon("scroll")` <a href="RAPDC_lecture3.html" title=>Конспект от 20.09</a> 

Домашнее задание: 

`r  shiny::icon("readme")`  <a href="https://disk.yandex.ru/i/V6oQg2xZeysiDg" title=>Kropko, Kubinec, 2020</a>  

Вопросы к статье:

1) Приведите примеры содержательных вопросов, на которые могут помочь ответить модели с FE на пространственные единицы; с FE на временные периоды.

2) Как реализуется внутригрупповое преобразование в FE-моделях на пространственные единицы? А в случае если модель с FE на временные периоды? 

3) В чем отличие интерпретации оценок коэффициентов при предикторах в моделях с FE на пространственные единицы по сравнению с соответствующей интерпретацией в моделях с FE на временные периоды?  

4) Как устроена twoways FE-model? В чем ограничения такой модели? Почему ее нередко называют tricky model? 

## Занятие 5
 
Тема: Модель с FE на временные периоды, twoways model, модель с разными наклонами

Домашнее задание (до 9 октября):

`r  shiny::icon("pencil")` <a href="RAPDC_bonus1_2022.pdf" title=>Бонус 1 (сдаваемое по желанию)</a>

Домашнее задание (до 14 октября): 

`r  shiny::icon("pencil")` <a href="RAPDC_hw1_2022.pdf" title=>Домашнее задание 1 (сдаваемое)</a> 

## Занятие 6
 
Тема: Модель с FE на временные периоды, twoways model, модель с разными наклонами

`r  shiny::icon("scroll")` <a href="RAPDC_seminar2_2022.pdf" title=>Семинарский листочек 2</a> 

`r  shiny::icon("desktop")` <a href="RAPDC_lab1_3.pdf" title=>Практикум</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_lectures4_5.html" title=>Конспект от 27.09 и 04.10</a> 

## Занятие 7 

Тема: проверочная работа, повторение, введение в модели со смешанными эффектами

Домашнее задание к 14 октября: 
 
1) прочитать стр. 218 -- 224 в статье Steenbergen,Jones, 2002 (ее можно найти в общей папке с литературой: под-папка ME-models)
 
2) подумать то, насколько содержательно оправданны допущения моделей со смешанными эффектами 
 
3) критически осмыслить предложенное авторами обоснование для использования этого класса моделей 

## Занятие 8

Тема: спецификация моделей со смешанными эффектами

## Занятие 9

Тема: допущения моделей со смешанными эффектами

`r  shiny::icon("scroll")` <a href="RAPDC_seminar3.pdf" title=>Семинарский листочек 3</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_Lectures_6_7.html" title=>Конспект от 14.10 и 18.10</a> 

## Занятие 10
 
Тема: практикум по моделям со смешанными эффектами (часть 1)

## Занятие 11
 
Тема: практикум по моделям со смешанными эффектами (часть 2)

`r  shiny::icon("scroll")` <a href="RAPDC_01.11_08.11.html" title=>Конспект от 01.11 и 08.11</a> 

Домашнее задание (до 23 ноября): 

`r  shiny::icon("pencil")` <a href="RAPDC_hw2_2022.pdf" title=>Домашнее задание 2 (сдаваемое)</a> 

## Занятие 12

Тема: рандомизированный эксперимент, средний эффект воздействия, допущения SUTVA 

`r  shiny::icon("scroll")` <a href="RAPDC_lecture.pdf" title=>Презентация</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_seminar4.pdf" title=>Семинарский листочек 4</a> 

## Занятие 13

Тема: выбор контрольных переменных, критерий черного хода

`r  shiny::icon("scroll")` <a href="RAPDC_seminar5_2022.pdf" title=>Семинарский листочек 5</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_seminar5_solution.pdf" title=>Конспект и решение семинара 5</a> 





